#!/usr/bin/env python


# Copyright JS Foundation and other contributors, http://js.foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import random
import os

def generate(DEST, SEED, COUNTER):

    file_to_open = os.path.join(DEST, "arithmetics-4.js")

    with open(file_to_open, "w") as file:

        file.write("//This file is generated by generate-arithmetics-4.py\n")

        MAX = 9007199254740991
        MIN = -9007199254740991

        random.seed(SEED)

        for i in range(COUNTER):

            N1 = random.randint(MIN, MAX)
            N2 = random.randint(MIN, MAX)
            if random.randint(0, 1):
                    N2 = random.randint(1, MAX)
            else:
                    N2 = random.randint(MIN, -1)

            # Difference between % operator in python and js
            # in python: -xxx % yy => yy - (abs(xxx) % yy)
            # in js: -xxx % yy => - abs(xxx) % yy
            if (((N1 < 0 and N2 > 0) or (N1 > 0 and N2 < 0)) and (N1 % N2 != 0) ):
                N3 = ((N1 % N2) - N2)
            else:
                N3 = (N1 % N2)

            file.write("assert ((%s) %% (%s) == (%s));\n" % (str(N1), str(N2), str(N3)))
            file.write("assert ((%s) %% (%s) != (%s));\n" % (str(N1), str(N2), str(int((N3) - 1))))
            file.write("assert ((%s) %% (%s) != (%s));\n" % (str(N1), str(N2), str(int((N3) + 1))))
