#!/usr/bin/env python


# Copyright JS Foundation and other contributors, http://js.foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import random
import os

def generate(DEST, SEED, COUNTER):

    file_to_open = os.path.join(DEST, "arithmetics-3.js")

    with open(file_to_open, "w") as file:

        file.write("//This file is generated by generate-arithmetics-3.py\n")

        COUNTER = 400
        MAX = 9007199254740991
        MIN = -9007199254740991
        MULTIPLIERMAX = 9999
        MULTIPLIERMIN = -9999
        MAXNUM = MAX / 2
        MINNUM = MIN / 2 + 1


        random.seed(SEED)

        for i in range(COUNTER):

            N1 = random.randint(MINNUM, MAXNUM)
            N2 = random.randint(MINNUM, MAXNUM)

            file.write("assert ((%s) + (%s) == (%s));\n" % (str(N1), str(N2), str(int(N1 + N2))))
            file.write("assert ((%s) + (%s) != (%s));\n" % (str(N1), str(N2), str(int(N1 + N2 - 1))))
            file.write("assert ((%s) + (%s) != (%s));\n" % (str(N1), str(N2), str(int(N1 + N2 + 1))))

            file.write("assert ((%s) - (%s) == (%s));\n" % (str(N1), str(N2), str(int(N1 - N2))))
            file.write("assert ((%s) - (%s) != (%s));\n" % (str(N1), str(N2), str(int(N1 - N2 - 1))))
            file.write("assert ((%s) - (%s) != (%s));\n" % (str(N1), str(N2), str(int(N1 - N2 + 1))))

        for i in range(COUNTER):

            N1 = random.randint(1, MAX)
            N2 = random.randint(1, MAX)

            file.write("assert ((%s) %% (%s) == (%s));\n" % (str(N1), str(N2), str(int(N1 % N2))))
            file.write("assert ((%s) %% (%s) != (%s));\n" % (str(N1), str(N2), str(int((N1 % N2) - 1))))
            file.write("assert ((%s) %% (%s) != (%s));\n" % (str(N1), str(N2), str(int((N1 % N2) + 1))))

        MINNUM = MIN / MULTIPLIERMAX + 1
        MAXNUM = MAX / MULTIPLIERMAX

        for i in range(COUNTER):

            N1 = random.randint(MINNUM, MAXNUM)
            N2 = random.randint(MULTIPLIERMIN, MULTIPLIERMAX)

            file.write("assert ((%s) * (%s) == (%s));\n" % (str(N1), str(N2), str(int(N1 * N2))))
            file.write("assert ((%s) * (%s) != (%s));\n" % (str(N1), str(N2), str(int((N1 * N2) - 1))))
            file.write("assert ((%s) * (%s) != (%s));\n" % (str(N1), str(N2), str(int((N1 * N2) + 1))))
